### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by NoahMarconi** [graalvm/fastr#4]
Hi, do you know what could be causing the build to fail? I see a few warnings:

```
8 warnings
Compiling com.oracle.truffle.r.parser with javac-daemon... [dependency TRUFFLE_R_PARSER_PROCESSOR updated]
Compiling com.oracle.truffle.tools.debug.shell with javac-daemon... [dependency TRUFFLE_DSL_PROCESSOR updated]
Downloading JFFI from ['https://lafo.ssw.uni-linz.ac.at/pub/graal-external-deps/jffi-1.2.9.jar', 'https://search.maven.org/remotecontent?filepath=com/github/jnr/jffi/1.2.9/jffi-1.2.9.jar']
Downloading https://lafo.ssw.uni-linz.ac.at/pub/graal-external-deps/jffi-1.2.9.jar to C:\Users\Noah\.mx\cache\JFFI_93294973285d2977c41fb1cfcfa864d41b145498.jar
Error reading from https://lafo.ssw.uni-linz.ac.at/pub/graal-external-deps/jffi-1.2.9.jar: HTTP Error 404: Not Found
** If behind a firewall without direct internet access, use the http_proxy environment variable (e.g. "env http_proxy=proxy.company.com:80 mx ...") or download manually with a web browser.
Traceback (most recent call last):
  File "C:\mx\/mx.py", line 12984, in <module>
    main()
  File "C:\mx\/mx.py", line 12968, in main
    retcode = c(command_args)
  File "C:\fastr\mx.fastr\mx_fastr.py", line 238, in build
    return mx_jvm().build(args)
  File "C:\fastr\mx.fastr\mx_fastr.py", line 57, in build
    return mx.build(args)
  File "C:\mx\/mx.py", line 8511, in build
    t.execute()
  File "C:\mx\/mx.py", line 607, in execute
    self.build()
  File "C:\mx\/mx.py", line 2657, in build
    self.subject.get_path(resolve=True)
  File "C:\mx\/mx.py", line 2609, in get_path
    return download_file_with_sha1(self.name, path, urls, self.sha1, sha1path, resolve, not self.optional, canSymlink=not bootClassPathAgent)
  File "C:\mx\/mx.py", line 2321, in download_file_with_sha1
    download(cachePath, urls)
  File "C:\mx\/mx.py", line 8242, in download
    os.remove(tmp)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Noah\\.mx\\cache\\JFFI_93294973285d2977c41fb1cfcfa864d41b145498.jar.qpwoug'

>[py27] C:\fastr>mx r

>[py27] C:\fastr>python C:\mx\/mx.py r
bash: C:fastretcldpaths: No such file or directory
etc/ldpaths does not define LD_LIBRARY_PATH
```

I'm not sure if it's the jffi 404 causing the failure or me trying to build on windows 8. I can run a VM if some kind of linux box would work better.

re the jffi 404 I don't see a 1.2.9 in that directory but do see a 1.2.7 if that helps pinpoint the problem.

**Comment by lukasstadler** [comment]
we currently do not support Windows as a platform, only linux, mac and solaris.
the error message is not really helpful - we will add a check that produces a proper message.

**Comment by NoahMarconi** [comment]
Thanks! I'll try a linux build.

**Comment by lukasstadler** [comment]
make sure to install libreadline-dev and gfortran - those are the two pieces that are usually missing on a vanilla linux installation.
